name: galavant
services:
  - name: web
    run_command: gunicorn galavant_pdm_anthony_canzona.galavant.wsgi:application --workers 3 --bind 0.0.0.0:$PORT
    environment_slug: python
    source_dir: ./
    http_port: 8080
    build_command: pip install -r requirements.txt
    release_command: python manage.py migrate