# Generated by Django 4.2 on 2024-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='place_name',
            field=models.CharField(default='needs updated', max_length=100),
        ),
        migrations.DeleteModel(
            name='LocationProfile',
        ),
    ]
