# Generated by Django 4.2 on 2024-07-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_profile_username_profile_bio_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='countries_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='places_saved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
