# Generated by Django 4.2.13 on 2024-08-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationuser',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.location'),
        ),
    ]
